apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapache-playbook
spec:
  selector:
    matchLabels:
      run: phpapache-playbook
  replicas: 3
  template:
    metadata:
      labels:
        run: phpapache-playbook
    spec:
      containers:
      - name: phpapache-playbook
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: phpapache-playbook
  labels:
    run: phpapache-playbook
spec:
  ports:
  - port: 80
  selector:
    run: php-apache-playbook
