apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapache
spec:
  selector:
    matchLabels:
      run: phpapache
  replicas: 2
  template:
    metadata:
      labels:
        run: phpapache
    spec:
      containers:
      - name: phpapache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: phpapache
  labels:
    run: phpapache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
