apiVersion: v1
kind: Pod
metadata:
  name: static-web2
  labels:
    role: myrole
spec:
  selector:
    matchLabels:
      run: static-web2
  replicas: 2
  template:
    metadata:
      labels:
        run: php    
  spec:
    containers:
      - name: static-web2
        image: nginx:alpine
        ports:
          - name: web
            containerPort: 8082
            protocol: TCP
#prueba

