apiVersion: v1
kind: Pod
metadata:
  name: static-web2
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx:alpine
      ports:
        - name: web
          containerPort: 8082
          protocol: TCP
