apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: static-web21
 labels:
   app: front

spec:
 replicas: 2 # We'll get three identical pods
 selector:
   matchLabels:
     app: front
 template:
   metadata:
     labels:
       app: front
   spec:
     containers:
      - name: static-web21
        image: nginx:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: service-static-web21
  namespace: default
  labels:
    app: front
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
