apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: chef-server
 labels:
   app: front
  
spec:
 replicas: 100 # We'll get three identical pods
 selector:
   matchLabels:
     app: front
 template:
   metadata:
     labels:
       app: front
   spec:
     containers:
      - name: nginx
        image: nginx:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  labels:
    app: front
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80